---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: ghcr.io/eficode-academy/quotes-flask-frontend:release
      ports:
        - containerPort: 5000
      env:
        - name: BACKEND_HOST
          value: 10.0.40.196
        - name: BACKEND_PORT
          value: '5000'
