apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/eficode-academy/quotes-flask-backend:release
        name: quotes-flask-backend
        imagePullPolicy: Always
        ### using hardcoded env vars
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: superuser
        - name: DB_PASSWORD
          value: complicated
        - name: DB_NAME
          value: quotes
